history:
	esri2geojson https://gisweb.charlottesville.org/gisweb/rest/services/Layers/MapServer/68 individually-protected-property.geojson
	esri2geojson https://gisweb.charlottesville.org/gisweb/rest/services/Layers/MapServer/69 adc-districts-contributing-structure.geojson
	esri2geojson https://gisweb.charlottesville.org/gisweb/rest/services/Layers/MapServer/70 adc-districts.geojson
